### ISSUE TITLE
Failed to fetch containers

### ISSUE THREAD

**Issue by jbeck22** [smashingtags/homelabarr#8]
I'm using the same docker compose file that you have listed here -- only thing that I changed were the port numbers so that they didn't interfere with other containers.

I think my issue is with the .env file.  What do I put for the CORS_ORIGIN section

Also -- where do I get the AUTH_Token

I'm running this on a Raspberry Pi 5 Raspbian OS version 6.6.62+rpt-rpi-2712

**Comment by smashingtags** [comment]
1. The auth has been removed and I just forgot to remove it from the readme.
2. The CORS origin can be set to  * to allow for all and it will work, or you can leave that out of the .env since it has a default built into the image of *
3. I was able to replicate the issue with changing the port, I will be working on getting that fixed up once I get time. I will probably patch it in the meantime by having the homelabarr-backend use a less-used port

**Comment by jbeck22** [comment]
Still getting the Failed to Fetch Containers error on the main screen.


**Here is my docker compose file**:

![Image](https://github.com/user-attachments/assets/7fcec11c-4c95-4215-a980-fe1b51f8b9be)


**Here is my .env file:**

![Image](https://github.com/user-attachments/assets/d425ac6e-1084-4501-8dcd-47bb754e2760)

**Comment by smashingtags** [comment]
See the closed PR here for how this was fixed [https://github.com/smashingtags/homelabarr/pull/10](url) or just refer to the yml below for how to write yours correctly and all should be good. 

Cheers!



```
services:
  frontend:
    image: ghcr.io/smashingtags/homelabarr-frontend:latest
    container_name: homelabarr-frontend
    restart: unless-stopped
    ports:
      - "8087:80"
    networks:
      - homelabarr
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://homelabarr-frontend/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  backend:
    image: ghcr.io/smashingtags/homelabarr-backend:latest
    container_name: homelabarr-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CORS_ORIGIN=*
      - DOCKER_SOCKET=/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3002:3001"
    networks:
      - homelabarr
    group_add:
      - "999"  # Docker group ID
    privileged: true  # Required for Docker socket access
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://homelabarr-backend:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
networks:
  homelabarr:
    name: homelabarr
```

**Comment by jbeck22** [comment]
I'm using the same compose file that you sent -- but I'm still getting the same error.

Is there a way to enable some logs so we can see where it is failing?

**Comment by jbeck22** [comment]
latest build fix my initial issues.  Now I can use the app.  Thanks!
